### ISSUE TITLE
DataTables::filterColumns() must be of the type array

### ISSUE THREAD

**Issue by mateomattmatt** [ACFBentveld/Laravel-datatables#13]
I am getting this error

Argument 1 passed to ACFBentveld\DataTables\DataTables::filterColumns() must be of the type array, null given, called in /vendor/acfbentveld/laravel-datatables/src/DataTables.php on line 142

this is the code:
\DataTables::model(new User)->get();

**Comment by wimurk** [comment]
This is fixed in version [v2.0.22](https://github.com/ACFBentveld/Laravel-datatables/releases/tag/v2.0.22)
