### ISSUE TITLE
Call to a member function each() on null when using collect() with empty data

### ISSUE THREAD

**Issue by AmandoVledder** [ACFBentveld/Laravel-datatables#16]
When using

```php
DataTables::collect($items)->get();
```

and `$items` happends to be empty you get

`Call to a member function each() on null` at [`DataTables.php` line `276`](https://github.com/ACFBentveld/Laravel-datatables/blob/244cdab8d13f938efc0e4dad6eb40bba72184edb/src/DataTables.php#L276).

The possible cause for this can be the `$model` variable being set to `null` on line [`272`](https://github.com/ACFBentveld/Laravel-datatables/blob/244cdab8d13f938efc0e4dad6eb40bba72184edb/src/DataTables.php#L272)

**Comment by wimurk** [comment]
Bug confirmed when parsing an empty ombject
