### ISSUE TITLE
Trouble with Setup 

### ISSUE THREAD

**Issue by Candersen1O** [ACFBentveld/Laravel-datatables#2]
I have been interested in using this in a project I'm working on.
I wanted to test it out and see if it would fit what I need, so I wanted to set up a test version of these DataTables following the Usage section of the README file. However, there are some sections that are glossed over making following how to use this a little unclear. For example, where is `$users = DataTables::model(new User)->get();` meant to go? I assumed that it goes in a controller function, but I'm honestly not sure.
Additionally I don't understand how the function and the dataTable connect (or why they aren't connecting). In Usage it says:

> Just get the data from the same url. The package will handle it all

and

> You don't have to specify a different url. The package will detect if the datatable makes connection

And that leaves me confused how to set this up. So I'm wondering if I could get some clearer instructions on how to set it up correctly.

**Comment by wimurk** [comment]
Hello @Candersen1O 
The [datatables](https://datatables.net/) uses the serverside method. This simply means, the table makes a request to the server (your controller) and expects a json response. This package caches the request and generates a json response with the data you provide. 

Sample : 
```php
//lets say the route is : myproject.com/users
public function index()
{
     \DataTables::model(new User)->get();
      return view('users.index');
}
```
Now in your view : 

```php
<table id="table">
   <thead>
      <tr>
        <th>Id</th>
        <th>Name</th>
      </tr>
  </thead>
</table>
```

And in your javascript
```javascript
 $(document).ready(function() {
    $('#datatable').DataTable({
        "processing": true, //default datatables
        "serverSide": true, //default datatables to make it server side
        "ajax": location.href, //This means it uses the same route and the same controller method this view comes from
        "columns": [ //define the keys
                { "data": "id" },
                { "data": "name" },
            ]
    });

} );
```
The javascript ` "serverSide": true,` creates a json request to the `ajax` url. For example `myproject.com/users`. The package caches this requests and starts generating the json response

**Comment by Candersen1O** [comment]
Thanks for responding!
I encounter a problem when trying to execute your example; the model method being used in the index function. 
I receive an error stating `Non-static method ACFBentveld\DataTables\DataTables::model() should not be called statically`. I made modification to call the model method statically (changed to `(new \ACFBentveld\DataTables\DataTables) -> model(new User)->get();`). Doing this does resolve the issue trying to access the route, but instead of viewing a page with a datatable on it, all I see is the User information that would be used in the datatable displayed as an array.

**Comment by wimurk** [comment]
@Candersen1O there was an issue with finding the draw request and is resolved in version [v2.0.7](https://github.com/ACFBentveld/Laravel-datatables/releases/tag/v2.0.7)
If you update to the new version you should be fine.

**Comment by Candersen1O** [comment]
The update worked! Thank you! 

Also thank you for the additional advice. I am testing multiple datatables though, which is why I need to specify which ones are being used.
Thank you again for helping me!

**Comment by wimurk** [comment]
No problem. Thank you for trying out this package
